In [ ]:
# method 31 : apply ()
df ["score_status"] = df["Creditscore"].apply

In [ ]:
# map method : () map method element wise strip 

In [ ]:
# numpy method in python 
import numpy as np 
numerical_data = 

In [ ]:
# method 32:  applymap ()  entire dataframe element wise  # we can make changes using apply map 
df.applymap(lambda x : round(x,2))

In [1]:
import numpy as np
# create the 1-- D array n - dimension 

In [3]:
arr_1d = np.array([1,2,3,4,5])  # how we create 1 - dimension 
arr_1d

array([1, 2, 3, 4, 5])

In [4]:
# two 2d Data 
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# create the 3d arrya
arr_3d = np.array([[[1,2,3],[4,5,6],[12,3,5]]])
arr_3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [12,  3,  5]]])

In [2]:
# create the 4D array
import numpy as np
arry_4d = np.array([[[[1,2,3,4,5],[2,3,4,5],[3,4,5,6]]]])
arr_4d

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (1, 1, 3) + inhomogeneous part.

In [11]:
arr_1d = np.array([1,2,3,4,5])  # how we create 1 - dimension 
print(arr_1d[1:3])

# 1d slice syntax : arr[start:stop:step]  


[2 3]


In [13]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [14]:
arr_2d[1:3,2:4]        # arr[start:stop:step]

array([[7, 8],
       [7, 6]])

In [17]:
arr_2d[1:,2:]

array([[7, 8],
       [7, 6]])

In [ ]:
# syntax 2d : arr[row_start:rows_stop,col]

In [21]:
arr_3d = np.array([[[1,2,3,4],
                    [3,4,5,6],
                    [5,6,3,4],
                    [4,5,5,6]],
                   [ [1,2,3,4],
                    [3,4,5,6],
                    [5,6,3,4],
                    [4,5,5,6]
                   ]
                  ])
arr_3d[0,1:3,1:3]


array([[4, 5],
       [6, 3]])

In [22]:
array_4d = np.array(
    [
        [
                [
                [1,2,3],
                [4,5,6],
                [7,8,9],
                ],
                [
                [10,11,12],
                [13,14,15],
                [16,17,18],
                ],
        ]
    ]
)
array_4d[1]

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]])

In [27]:
import numpy as np
array_4d = np.array(
    [
        [
                [
                [1,2,3],
                [4,5,6],
                [7,8,9],
                ],
                [
                [10,11,12],
                [13,14,15],
                [16,17,18],
                ],
        ]
    ]
)
array_4d[0,1,1:,0:2]

array([[13, 14],
       [16, 17]])

In [ ]:
1d = [column ]
2D = [Row , colum]
3D = [block.row,cloumn]
4D = [group,block,row,column]

# syntax  : [group,block,row-start:row-stop,col-strt:,colum-stop]

In [29]:
# chek the dimension ndim () method to find the dimension of array 
arr_2d.ndim

2

In [30]:
# Array of Zeros 
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
#5 array of ones 
arr = np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# 6 identity matrix   # it creates digonal matrix 
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
# create the range using : arange (2,15,2)
import numpy as np
arr_range = np.arange(2,15,2)
arr_range


array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
# with step size 

In [4]:
# create the line space  # create the space between values 
line_space = np.linspace(0,1,5)
line_space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
# create the line space  # create the space between values 
line_space = np.linspace(0,1,100) # 0 - 1 ke bech ka sara data 
line_space

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [7]:
# create the random array   
array = np.random.rand(3,4)
array

array([[0.68029403, 0.27549011, 0.60062216, 0.12402004],
       [0.71044548, 0.14370619, 0.47609774, 0.11087093],
       [0.72758382, 0.66338163, 0.16988697, 0.12906246]])

In [8]:
# create the random array   (start,stop,totalvalues ) random decimal values comes between 0-1
array = np.random.rand(10,4) # 10 rows 4 coloms )
array

array([[0.63884463, 0.65179173, 0.73049196, 0.05085263],
       [0.6769462 , 0.40956619, 0.1598522 , 0.38709012],
       [0.05771392, 0.71032836, 0.97335926, 0.51297318],
       [0.31568009, 0.84661301, 0.84012482, 0.06866682],
       [0.39507567, 0.19437103, 0.20997604, 0.66370054],
       [0.8769698 , 0.84872623, 0.36356775, 0.96433685],
       [0.54962063, 0.10998495, 0.08866239, 0.71389139],
       [0.56957583, 0.30074591, 0.71812139, 0.09098934],
       [0.23245658, 0.45430637, 0.63466899, 0.80908646],
       [0.01910448, 0.61779315, 0.35906817, 0.95080654]])

# 10 method Random integer array 


In [9]:
#CREATE the random integer array 
array = np.random.randint(1,10,(4,4))# (start,end(row,colom))
array

array([[7, 3, 2, 9],
       [7, 9, 2, 1],
       [8, 1, 7, 7],
       [6, 8, 8, 9]], dtype=int32)

In [12]:
#CREATE the random integer array 
array = np.random.randint(1,10,100)# (start,end(row,colom))
array

array([3, 6, 7, 2, 9, 2, 4, 3, 1, 1, 7, 3, 2, 5, 7, 5, 8, 8, 6, 6, 9, 3,
       9, 4, 5, 1, 7, 2, 8, 3, 4, 2, 7, 7, 8, 9, 5, 6, 4, 5, 3, 7, 9, 7,
       3, 2, 5, 9, 4, 6, 2, 3, 3, 7, 1, 9, 1, 1, 7, 3, 7, 6, 2, 9, 9, 8,
       1, 8, 6, 1, 3, 6, 8, 9, 1, 2, 2, 9, 1, 8, 6, 1, 8, 4, 2, 9, 3, 6,
       5, 7, 7, 4, 3, 6, 5, 3, 3, 2, 9, 4], dtype=int32)

In [43]:
#CREATE the random integer array 
age = np.random.randint(20,30,100)# (start,end(row,colom))
sort.age()

SyntaxError: invalid syntax (2478044387.py, line 3)

In [17]:
# 11 methods Convert list into numpy arrar 
my_list = [1,2,3,4,5,5]
array = np.array(my_list)
my_list

[1, 2, 3, 4, 5, 5]

In [19]:
# create the 2 d array 
array = np.array([[1,2,3,4],
                  [2,3,4,5]])
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [20]:
# method 1 : shape #( rows and colomns ) in number form 
array.shape


(2, 4)

In [21]:
# check the dimenstion of array 
# array mens collection of homogenious values is called array 

# method  2 : ndim chek the dimension of the array
array.ndim

2

In [22]:
# check the dtype of value 
# METHOD 3 :dtype 
array.dtype  # what is int64 ,int32 =  1byte = 8 bit , int 28 bytes ,  28 * 8 = 224 , 1 mega bit = 125000 1mb 

dtype('int64')

In [23]:
# itemsize method () 
array.itemsize

8

In [24]:
# check memory of array 
array.size

8

# transpose the array ( rows is become colomns and colomns is become a rows ) it is transpose array 

In [25]:
array.T    

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [26]:
# create the complex number  it is of real and imaginary both mixture that is complex 
# this using find real number  
a = np.array([1+2j, 3+4j]) # ([real number ,imagineari number ])

a.real

array([1., 3.])

In [27]:
# how to find imaginary number 
a.imag

array([2., 4.])

In [ ]:
# flat method # converts array into iterator 
# all 3* 3 = 9  multi dimension into single dimension array 


In [ ]:
# 1 . 

In [29]:
array 

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [30]:
# column wise sum
# arr.sum(axis=0)
array.sum(axis = 0) # 0 mens columns wise sum 

array([3, 5, 7, 9])

In [31]:
# column wise sum
# arr.sum(axis=0)
array.sum(axis = 1) # 1 mens row wise sum


array([10, 14])

In [ ]:
# row wise 

In [33]:
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [32]:
# reshape ()
# changes shape of array by the method 
a = np.array([1,2,3,4,5,6])

a.reshape(2,3) 

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# reshape ()
# changes shape of array by the method 
a = np.array([1,2,3,4,5,6])

a.reshape(3,2) 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
# count_nonzero()


In [46]:
# SORT () TO SORT THE ARRAY 


In [49]:
name = ["male","female"]

Gender = np.random.choice(name,100)
Gender

array(['female', 'male', 'male', 'male', 'female', 'female', 'female',
       'male', 'female', 'male', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'female', 'female', 'female', 'male', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'male', 'female', 'male', 'female', 'female', 'female',
       'female', 'male', 'female', 'male', 'male', 'female', 'female',
       'female', 'male', 'female', 'female', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'female', 'male', 'female',
       'female', 'male', 'female', 'female', 'male', 'female', 'male',
       'male', 'male', 'male', 'male', 'male', 'male', 'female'],
      dty

In [50]:
# generate the integer columns  using 

salary = np.random.uniform(10000,25000,100)
salary

array([11348.53631647, 15614.42805652, 10957.60397562, 21465.731625  ,
       24501.11660497, 10974.92072465, 14000.017365  , 23388.02365035,
       14263.87196152, 23392.60380432, 16322.8222302 , 10935.84435887,
       21468.41916058, 12573.19648564, 11241.14565322, 11977.90837093,
       10737.34918648, 10496.37360533, 13456.83250012, 17007.26741032,
       16612.51039368, 23854.30413292, 19777.04265938, 23687.67669449,
       17051.98050507, 12191.26119671, 20403.97924809, 24434.78620093,
       22580.31782789, 11529.0282473 , 23483.47256353, 11714.3785198 ,
       23041.48733136, 14292.4297111 , 15854.94361406, 23340.56818895,
       14648.30969794, 22562.16053673, 15504.75096446, 17993.85727983,
       11062.49426166, 11125.26616904, 15218.82046415, 20617.55456785,
       23991.48839992, 15543.80630108, 13426.98550286, 24998.95374415,
       10265.95809499, 19301.34493394, 21736.34155913, 17258.61588628,
       10554.07655459, 24685.60716253, 18558.05301114, 23880.23880609,
      

In [52]:
# generate the integer columns  using .uniform

salary = np.random.uniform(10000,25000,100)
np.round(salary,2)  # from the salary i want to take only 2 rounds 

array([13010.08, 19973.55, 24601.36, 10371.13, 15307.09, 11091.1 ,
       23335.88, 18503.84, 21301.29, 14365.45, 17193.58, 10183.05,
       18763.75, 14605.53, 11240.72, 20816.85, 14496.4 , 23003.58,
       20647.85, 17076.27, 15974.08, 14479.34, 19975.28, 17058.32,
       24782.75, 10242.14, 23508.84, 16586.99, 10446.21, 12412.41,
       14563.49, 15907.09, 16691.18, 12234.52, 16505.83, 22609.74,
       17552.08, 22412.  , 18730.52, 18297.7 , 18385.91, 17267.78,
       11770.26, 13833.16, 12385.88, 11578.27, 10363.39, 14346.4 ,
       12939.63, 22933.7 , 18214.88, 10545.67, 18011.78, 18966.3 ,
       11273.77, 13653.03, 13505.09, 24462.78, 23565.07, 15295.6 ,
       10169.04, 17087.88, 20267.85, 21996.34, 18344.91, 14511.2 ,
       13486.05, 22044.93, 13703.2 , 23537.35, 15696.68, 13502.58,
       21884.53, 12919.96, 10108.89, 23329.25, 10200.59, 12795.17,
       18452.44, 16908.45, 11446.68, 10799.94, 19080.26, 23391.56,
       10055.12, 13952.91, 18766.93, 21157.79, 11693.24, 23300

In [53]:
Age = np.random.randint(22,30,100)
Age

array([25, 23, 22, 26, 24, 27, 24, 28, 28, 26, 24, 28, 23, 22, 26, 23, 25,
       28, 23, 26, 26, 25, 28, 22, 25, 25, 24, 22, 25, 22, 23, 27, 25, 27,
       28, 25, 23, 22, 23, 29, 22, 23, 24, 27, 29, 29, 29, 29, 26, 22, 23,
       22, 26, 23, 29, 28, 27, 25, 25, 27, 22, 26, 26, 22, 23, 29, 23, 27,
       24, 27, 29, 27, 27, 23, 27, 23, 23, 27, 27, 23, 29, 28, 27, 22, 27,
       23, 22, 22, 26, 26, 25, 28, 27, 25, 28, 27, 29, 29, 22, 25],
      dtype=int32)

In [61]:
# id : 100
# Name 
# Gender 
# Dept
# Exp
# Role
# salary
# size 500 * 7 
import numpy as np
columns = ["id","Name","Dept","Exp","Role","salary"]
print(columns)

['id', 'Name', 'Dept', 'Exp', 'Role', 'salary']


In [65]:
id  = np.arange(0,100)
id

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [66]:
Name =np.array(["Nayan","yash","punit","Himanshu","Danish","sitara","pitara","khatara"])

Name = g


array(['Nayan', 'yash', 'punit', 'Himanshu'], dtype='<U8')

In [73]:
Name =np.resize(Name,500)
Name

array(['Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Names', 'Names', 'Names', 'Names', 'Names', 'Names',
       'Names', 'Nam

In [ ]:
dept =
dept.np.random.choice(dept,100)

# Exp 
exp = np.random.uniform(1,20,100)
exp = np.round(exp,1)

 # role 

role =["Devloper","Testing","Data Scientist","AI Engieer","Devops"]

Role = np.random.choice(role,100)
 # salary 
salary = np.random.uniform(45000,100000,100)
salary = np.round(salary,2)


In [ ]:
df = pd.DataFrame({ "ID":ID "Name":Name,"Gender":Gender,"Department":dept,"Exp":Exp,"salary":salary})

In [ ]:
df.head()

In [ ]:
# Question 

In [4]:
# id  : 100
# Name 
# Gender
# Dept
# Exp
# Role 
# Salary


# ID 
ID =  np.arange(100,200)



# name :

name = ["Sumit","Vaishnavi","Ayushi","Sameer","Sahil","Neha","Rahul","Danish","Sitara","Haritha","Akshitha"]

Name = np.random.choice(name,100)


# gender

g = ["Male","Female"]
Gender =  np.random.choice(g,100)

# dept

dept= ["IT","Finace","HR","Inventory","Call Center","Science"]

Dept = np.random.choice(dept,100)

# Exp 

exp = np.random.uniform(1,20,100)
exp = np.round(exp,1)
exp

# role

role = ["Devloper","Testing","Data Scientist","AI Engineer","Devops"]

Role = np.random.choice(role,100)

# salary

salary = np.random.uniform(45000, 100000,100)
salary = np.round(salary,2)
 
len(salary)

100

In [5]:
import pandas as pd
df = pd.DataFrame({
    "ID":ID,
    "Name":Name,
    "Gender":Gender,
    "Department":Dept,
    "Exp":exp,
    "Job Role":Role,
    "Salary":salary
})

In [7]:
df.head(10)

,ID,Name,Gender,Department,Exp,Job Role,Salary
0,100,Sameer,Female,Call Center,14.5,AI Engineer,63712.24
1,101,Sitara,Male,Inventory,7.8,Devloper,89148.26
2,102,Haritha,Male,Science,2.1,Testing,89767.31
3,103,Neha,Female,Inventory,13.2,Testing,97267.56
4,104,Sameer,Male,HR,2.4,Devops,75028.59
5,105,Sitara,Female,Inventory,8.7,Devops,92236.01
6,106,Neha,Female,Call Center,6.7,Devloper,88695.20
7,107,Neha,Male,Finace,3.7,Devops,85074.21
8,108,Sitara,Female,Science,4.3,Devops,79407.03
9,109,Haritha,Male,Science,5.6,AI Engineer,52229.56
